[package]
name = "triagebot"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
serde_json = "1"
openssl = "0.10"
dotenv = "0.14"
reqwest = { version = "0.10", features = ["json"] }
regex = "1"
lazy_static = "1"
log = "0.4"
anyhow = "1"
hex = "0.4"
env_logger = "0.7"
parser = { path = "parser" }
rust_team_data = { git = "https://github.com/rust-lang/team" }
glob = "0.3.0"
toml = "0.5.1"
hyper = "0.12.32"
futures = { version = "0.3", default-features = false, features = ["compat"] }
uuid = { version = "0.8", features = ["v4"] }
url = "2.1.0"
once_cell = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[profile.release]
debug = 2
