[package]
name = "triagebot"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
serde_json = "1"
openssl = "0.10"
dotenv = "0.14"
reqwest = "0.9"
regex = "1"
lazy_static = "1"
log = "0.4"
anyhow = "1"
hex = "0.3.2"
env_logger = "0.6"
parser = { path = "parser" }
rust_team_data = { git = "https://github.com/rust-lang/team" }
glob = "0.3.0"
toml = "0.5.1"
hyper = "0.12.32"
futures-preview = { version = "=0.3.0-alpha.17", features = ["compat"] }
uuid = { version = "0.7.4", features = ["v4"] }
url = "2.1.0"
once_cell = "0.2.2"

[dependencies.serde]
version = "1"
features = ["derive"]

[profile.release]
debug = 2
